export const CHANGE_SEARCHFIELD = "CHANGE_SEARCHFIELD";
export const GET_ROBOTS_PENDING = "GET_ROBOTS_PENDING";
export const GET_ROBOTS_SUCCESS = "GET_ROBOTS_SUCCESS";
export const GET_ROBOTS_FAIL = "GET_ROBOTS_FAIL";
